#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cisco-Accounting
version:      1.01
version_from: lib/Cisco/Accounting.pm
installdirs:  site
requires:
    Net::Telnet::Wrapper:          0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
